/*
 * Hardware modules present on the AM43xx chips
 *
 * Copyright (C) 2013 Texas Instruments Incorporated - http://www.ti.com
 *
 * Paul Walmsley
 * Benoit Cousson
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/io.h>
#include <linux/platform_data/gpio-omap.h>
#include <linux/power/smartreflex.h>
#include <linux/platform_data/omap_ocp2scp.h>
#include <linux/i2c-omap.h>

#include <linux/omap-dma.h>
#include <linux/platform_data/spi-omap2-mcspi.h>
#include <linux/platform_data/asoc-ti-mcbsp.h>
#include <plat/dmtimer.h>

#include "omap_hwmod.h"
#include "omap_hwmod_common_data.h"
#include "cm43xx.h"
#include "prm43xx.h"
#include "prm-regbits-43xx.h"
#include "i2c.h"
#include "mmc.h"
#include "wd_timer.h"

/* Base offset for all AM43XX interrupts external to MPUSS */
#define AM43XX_IRQ_GIC_START	32

/* Base offset for all AM43XX dma requests */
#define AM43XX_DMA_REQ_START	1


/*
 * IP blocks
 */

/*
 * 'l3' class
 * instance(s): l3
 */
static struct omap_hwmod_class am43xx_l3_hwmod_class = {
	.name	= "l3",
};

/* l3 */
static struct omap_hwmod am43xx_l3_hwmod = {
	.name		= "l3",
	.class		= &am43xx_l3_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_L3_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_L3_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'l4_hs' class
 * instance(s): l4_hs
 */
static struct omap_hwmod_class am43xx_l4_hs_hwmod_class = {
	.name	= "l4_hs",
};

/* l4_hs */
static struct omap_hwmod am43xx_l4_hs_hwmod = {
	.name		= "l4_hs",
	.class		= &am43xx_l4_hs_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.prcm = {
		.omap4 = {
			.flags = HWMOD_OMAP4_NO_CONTEXT_LOSS_BIT,
		},
	},
};

/*
 * 'l4fw' class
 * instance(s): l4fw
 */
static struct omap_hwmod_class am43xx_l4fw_hwmod_class = {
	.name	= "l4fw",
};

/* l4fw */
static struct omap_hwmod am43xx_l4fw_hwmod = {
	.name		= "l4fw",
	.class		= &am43xx_l4fw_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_L4FW_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_L4FW_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'l4ls' class
 * instance(s): l4ls
 */
static struct omap_hwmod_class am43xx_l4ls_hwmod_class = {
	.name	= "l4ls",
};

/* l4ls */
static struct omap_hwmod am43xx_l4ls_hwmod = {
	.name		= "l4ls",
	.class		= &am43xx_l4ls_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_L4LS_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_L4LS_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'l4wkup' class
 * instance(s): l4wkup
 */
static struct omap_hwmod_class am43xx_l4wkup_hwmod_class = {
	.name	= "l4wkup",
};

/* l4wkup */
static struct omap_hwmod am43xx_l4wkup_hwmod = {
	.name		= "l4wkup",
	.class		= &am43xx_l4wkup_hwmod_class,
	.clkdm_name	= "l4_wkup_aon_clkdm",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_L4WKUP_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_L4WKUP_CONTEXT_OFFSET,
		},
	},
};

/*
 * 'ocp_wp_noc' class
 * instance(s): ocp_wp_noc
 */
static struct omap_hwmod_class am43xx_ocp_wp_noc_hwmod_class = {
	.name	= "ocp_wp_noc",
};

/* ocp_wp_noc */
static struct omap_hwmod am43xx_ocp_wp_noc_hwmod = {
	.name		= "ocp_wp_noc",
	.class		= &am43xx_ocp_wp_noc_hwmod_class,
	.clkdm_name	= "ocpwp_l3_clkdm",
	.prcm = {
		.omap4 = {
			.flags = HWMOD_OMAP4_NO_CONTEXT_LOSS_BIT,
		},
	},
};

/*
 * 'adc_tsc' class
 *
 */

static struct omap_hwmod_class am43xx_adc_tsc_hwmod_class = {
	.name	= "adc_tsc",
};

/* adc_tsc */
static struct omap_hwmod_irq_info am43xx_adc_tsc_irqs[] = {
	{ .irq = 16 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_adc_tsc_sdma_reqs[] = {
	{ .name = "dreq0", .dma_req = 53 + AM43XX_DMA_REQ_START },
	{ .name = "dreq1", .dma_req = 57 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_adc_tsc_hwmod = {
	.name		= "adc_tsc",
	.class		= &am43xx_adc_tsc_hwmod_class,
	.clkdm_name	= "l3s_tsc_clkdm",
	.mpu_irqs	= am43xx_adc_tsc_irqs,
	.sdma_reqs	= am43xx_adc_tsc_sdma_reqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
#if 0
			.clkctrl_offs = AM43XX_CM_WKUP_ADC_TSC_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_ADC_TSC_CONTEXT_OFFSET,
#endif 
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'aes' class
 *
 */

/* The IP is not compliant to type1 / type2 scheme */
static struct omap_hwmod_sysc_fields omap_hwmod_sysc_type_aes = {
	.sidle_shift	= 2,
	.srst_shift	= 1,
	.autoidle_shift	= 0,
};

static struct omap_hwmod_class_sysconfig am43xx_aes_sysc = {
	.rev_offs	= 0x100080,
	.sysc_offs	= 0x0084,
	.syss_offs	= 0x0088,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type_aes,
};

static struct omap_hwmod_class am43xx_aes_hwmod_class = {
	.name	= "aes",
	.sysc	= &am43xx_aes_sysc,
};

/* aes0 */
static struct omap_hwmod am43xx_aes0_hwmod = {
	.name		= "aes0",
	.class		= &am43xx_aes_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_AES0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_AES0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'cefuse' class
 *
 */

static struct omap_hwmod_class am43xx_cefuse_hwmod_class = {
	.name	= "cefuse",
};

/* cefuse */
static struct omap_hwmod am43xx_cefuse_hwmod = {
	.name		= "cefuse",
	.class		= &am43xx_cefuse_hwmod_class,
	.clkdm_name	= "l4_cefuse_clkdm",
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_CEFUSE_CEFUSE_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_CEFUSE_CEFUSE_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'control' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_control_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0010,
	.sysc_flags	= (SYSC_HAS_EMUFREE | SYSC_HAS_SIDLEMODE),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type2,
};

static struct omap_hwmod_class am43xx_control_hwmod_class = {
	.name	= "control",
	.sysc	= &am43xx_control_sysc,
};

/* control */
static struct omap_hwmod am43xx_control_hwmod = {
	.name		= "control",
	.class		= &am43xx_control_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_CONTROL_CLKCTRL_OFFSET,
			.flags = HWMOD_OMAP4_NO_CONTEXT_LOSS_BIT,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'cryptodma' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_cryptodma_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x002c,
	.syss_offs	= 0x0028,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_CLOCKACTIVITY |
			   SYSC_HAS_EMUFREE | SYSC_HAS_MIDLEMODE |
			   SYSC_HAS_SIDLEMODE | SYSC_HAS_SOFTRESET |
			   SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP | MSTANDBY_FORCE | MSTANDBY_NO |
			   MSTANDBY_SMART | MSTANDBY_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_cryptodma_hwmod_class = {
	.name	= "cryptodma",
	.sysc	= &am43xx_cryptodma_sysc,
};

/* cryptodma */
static struct omap_hwmod_irq_info am43xx_cryptodma_irqs[] = {
	{ .name = "irq0", .irq = 116 + AM43XX_IRQ_GIC_START },
	{ .name = "irq1", .irq = 117 + AM43XX_IRQ_GIC_START },
	{ .name = "irq2", .irq = 118 + AM43XX_IRQ_GIC_START },
	{ .name = "irq3", .irq = 119 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_cryptodma_hwmod = {
	.name		= "cryptodma",
	.class		= &am43xx_cryptodma_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.mpu_irqs	= am43xx_cryptodma_irqs,
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_CRYPTODMA_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_CRYPTODMA_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'dcan' class
 *
 */

static struct omap_hwmod_class am43xx_dcan_hwmod_class = {
	.name	= "dcan",
};

/* dcan0 */
static struct omap_hwmod_irq_info am43xx_dcan0_irqs[] = {
	{ .name = "parity", .irq = 51 + AM43XX_IRQ_GIC_START },
	{ .name = "int0", .irq = 52 + AM43XX_IRQ_GIC_START },
	{ .name = "int1", .irq = 53 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_dcan0_sdma_reqs[] = {
	{ .name = "dreq1", .dma_req = 40 + AM43XX_DMA_REQ_START },
	{ .name = "dreq2", .dma_req = 41 + AM43XX_DMA_REQ_START },
	{ .name = "dreq3", .dma_req = 47 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_dcan0_hwmod = {
	.name		= "dcan0",
	.class		= &am43xx_dcan_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_dcan0_irqs,
	.sdma_reqs	= am43xx_dcan0_sdma_reqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_DCAN0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_DCAN0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* dcan1 */
static struct omap_hwmod_irq_info am43xx_dcan1_irqs[] = {
	{ .name = "int0", .irq = 49 + AM43XX_IRQ_GIC_START },
	{ .name = "int1", .irq = 56 + AM43XX_IRQ_GIC_START },
	{ .name = "parity", .irq = 57 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_dcan1_hwmod = {
	.name		= "dcan1",
	.class		= &am43xx_dcan_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_dcan1_irqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_DCAN1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_DCAN1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'debugss' class
 *
 */

static struct omap_hwmod_class am43xx_debugss_hwmod_class = {
	.name	= "debugss",
};

/* debugss */
static struct omap_hwmod_irq_info am43xx_debugss_irqs[] = {
	{ .irq = 1 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_debugss_hwmod = {
	.name		= "debugss",
	.class		= &am43xx_debugss_hwmod_class,
	.clkdm_name	= "l3_aon_clkdm",
	.mpu_irqs	= am43xx_debugss_irqs,
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_DEBUGSS_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_DEBUGSS_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'des' class
 *
 */

/* The IP is not compliant to type1 / type2 scheme */
static struct omap_hwmod_sysc_fields omap_hwmod_sysc_type_des = {
	.sidle_shift	= 2,
	.srst_shift	= 1,
	.autoidle_shift	= 0,
};

static struct omap_hwmod_class_sysconfig am43xx_des_sysc = {
	.rev_offs	= 0x100030,
	.sysc_offs	= 0x0034,
	.syss_offs	= 0x0038,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type_des,
};

static struct omap_hwmod_class am43xx_des_hwmod_class = {
	.name	= "des",
	.sysc	= &am43xx_des_sysc,
};

/* des */
static struct omap_hwmod_irq_info am43xx_des_irqs[] = {
	{ .name = "s", .irq = 105 + AM43XX_IRQ_GIC_START },
	{ .name = "p", .irq = 130 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_des_sdma_reqs[] = {
	{ .name = "ctxindes_p", .dma_req = 32 + AM43XX_DMA_REQ_START },
	{ .name = "indes_p", .dma_req = 33 + AM43XX_DMA_REQ_START },
	{ .name = "outdes_p", .dma_req = 34 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_des_hwmod = {
	.name		= "des",
	.class		= &am43xx_des_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.mpu_irqs	= am43xx_des_irqs,
	.sdma_reqs	= am43xx_des_sdma_reqs,
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_DES_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_DES_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'dss' class
 *
 */

static struct omap_hwmod_class am43xx_dss_hwmod_class = {
	.name	= "dss",
};

/* dss */
static struct omap_hwmod_irq_info am43xx_dss_irqs[] = {
	{ .irq = 127 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_dss_hwmod = {
	.name		= "dss",
	.class		= &am43xx_dss_hwmod_class,
	.clkdm_name	= "dss_clkdm",
	.mpu_irqs	= am43xx_dss_irqs,
	.main_clk	= "disp_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_DSS_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_DSS_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'elm' class
 *
 */

static struct omap_hwmod_class am43xx_elm_hwmod_class = {
	.name	= "elm",
};

/* elm */
static struct omap_hwmod_irq_info am43xx_elm_irqs[] = {
	{ .irq = 4 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_elm_hwmod = {
	.name		= "elm",
	.class		= &am43xx_elm_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_elm_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_ELM_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_ELM_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'emif' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_emif_sysc = {
	.rev_offs	= 0x0000,
};

static struct omap_hwmod_class am43xx_emif_hwmod_class = {
	.name	= "emif",
	.sysc	= &am43xx_emif_sysc,
};

/* emif */
static struct omap_hwmod_irq_info am43xx_emif_irqs[] = {
	{ .irq = 101 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_emif_hwmod = {
	.name		= "emif",
	.class		= &am43xx_emif_hwmod_class,
	.clkdm_name	= "emif_clkdm",
	.mpu_irqs	= am43xx_emif_irqs,
	.main_clk	= "dpll_ddr_m4x2_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EMIF_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EMIF_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'epwmss' class
 *
 */

static struct omap_hwmod_class am43xx_epwmss_hwmod_class = {
	.name	= "epwmss",
};

/* epwmss1 */
static struct omap_hwmod am43xx_epwmss1_hwmod = {
	.name		= "epwmss1",
	.class		= &am43xx_epwmss_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EPWMSS1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EPWMSS1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* epwmss2 */
static struct omap_hwmod am43xx_epwmss2_hwmod = {
	.name		= "epwmss2",
	.class		= &am43xx_epwmss_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EPWMSS2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EPWMSS2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* epwmss3 */
static struct omap_hwmod am43xx_epwmss3_hwmod = {
	.name		= "epwmss3",
	.class		= &am43xx_epwmss_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EPWMSS3_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EPWMSS3_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* epwmss4 */
static struct omap_hwmod am43xx_epwmss4_hwmod = {
	.name		= "epwmss4",
	.class		= &am43xx_epwmss_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EPWMSS4_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EPWMSS4_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* epwmss5 */
static struct omap_hwmod am43xx_epwmss5_hwmod = {
	.name		= "epwmss5",
	.class		= &am43xx_epwmss_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_EPWMSS5_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_EPWMSS5_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'ermc' class
 *
 */

static struct omap_hwmod_class am43xx_ermc_hwmod_class = {
	.name	= "ermc",
};

/* ermc */
static struct omap_hwmod am43xx_ermc_hwmod = {
	.name		= "ermc",
	.class		= &am43xx_ermc_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_ERMC_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_ERMC_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'gfx' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_gfx_sysc = {
	.rev_offs	= 0x0014,
};

static struct omap_hwmod_class am43xx_gfx_hwmod_class = {
	.name	= "gfx",
	.sysc	= &am43xx_gfx_sysc,
};

/* gfx */
static struct omap_hwmod_irq_info am43xx_gfx_irqs[] = {
	{ .irq = 37 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_gfx_hwmod = {
	.name		= "gfx",
	.class		= &am43xx_gfx_hwmod_class,
	.clkdm_name	= "gfx_l3_clkdm",
	.mpu_irqs	= am43xx_gfx_irqs,
	.main_clk	= "div_gfx_fclk",
	.prcm = {
		.omap4 = {
			.flags = HWMOD_OMAP4_NO_CONTEXT_LOSS_BIT,
		},
	},
};

/*
 * 'gpio' class
 *
 * This class contains several variants: ['gpio', 'gpio']
 */

static struct omap_hwmod_class_sysconfig am43xx_gpio_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0010,
	.syss_offs	= 0x0114,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_ENAWAKEUP |
			   SYSC_HAS_SIDLEMODE | SYSC_HAS_SOFTRESET |
			   SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_gpio_hwmod_class = {
	.name	= "gpio",
	.sysc	= &am43xx_gpio_sysc,
};

/* gpio0 */
static struct omap_hwmod_irq_info am43xx_gpio0_irqs[] = {
	{ .name = "inta", .irq = 96 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 97 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_gpio0_sdma_reqs[] = {
	{ .dma_req = 22 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_gpio0_hwmod = {
	.name		= "gpio0",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_gpio0_irqs,
	.sdma_reqs	= am43xx_gpio0_sdma_reqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_GPIO0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_GPIO0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* gpio1 */
static struct omap_hwmod_irq_info am43xx_gpio1_irqs[] = {
	{ .name = "inta", .irq = 98 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 99 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_gpio1_sdma_reqs[] = {
	{ .dma_req = 23 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_gpio1_hwmod = {
	.name		= "gpio1",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_gpio1_irqs,
	.sdma_reqs	= am43xx_gpio1_sdma_reqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPIO1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPIO1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* gpio2 */
static struct omap_hwmod_irq_info am43xx_gpio2_irqs[] = {
	{ .name = "inta", .irq = 32 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 33 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_gpio2_hwmod = {
	.name		= "gpio2",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_gpio2_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPIO2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPIO2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* gpio3 */
static struct omap_hwmod_irq_info am43xx_gpio3_irqs[] = {
	{ .name = "inta", .irq = 62 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 63 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_gpio3_hwmod = {
	.name		= "gpio3",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_gpio3_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPIO3_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPIO3_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* gpio4 */
static struct omap_hwmod_irq_info am43xx_gpio4_irqs[] = {
	{ .name = "inta", .irq = 106 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 107 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_gpio4_hwmod = {
	.name		= "gpio4",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_gpio4_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPIO4_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPIO4_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* gpio5 */
static struct omap_hwmod_irq_info am43xx_gpio5_irqs[] = {
	{ .name = "inta", .irq = 148 + AM43XX_IRQ_GIC_START },
	{ .name = "intb", .irq = 149 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_gpio5_sdma_reqs[] = {
	{ .dma_req = 13 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_gpio5_hwmod = {
	.name		= "gpio5",
	.class		= &am43xx_gpio_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_gpio5_irqs,
	.sdma_reqs	= am43xx_gpio5_sdma_reqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPIO5_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPIO5_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'gpmc' class
 *
 */

static struct omap_hwmod_class am43xx_gpmc_hwmod_class = {
	.name	= "gpmc",
};

/* gpmc */
static struct omap_hwmod_irq_info am43xx_gpmc_irqs[] = {
	{ .irq = 100 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_gpmc_sdma_reqs[] = {
	{ .dma_req = 52 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_gpmc_hwmod = {
	.name		= "gpmc",
	.class		= &am43xx_gpmc_hwmod_class,
	.clkdm_name	= "l3s_clkdm",
	.mpu_irqs	= am43xx_gpmc_irqs,
	.sdma_reqs	= am43xx_gpmc_sdma_reqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_GPMC_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_GPMC_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'hdq1w' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_hdq1w_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0014,
	.syss_offs	= 0x0018,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_SOFTRESET |
			   SYSS_HAS_RESET_STATUS),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_hdq1w_hwmod_class = {
	.name	= "hdq1w",
	.sysc	= &am43xx_hdq1w_sysc,
};

/* hdq1w */
static struct omap_hwmod_irq_info am43xx_hdq1w_irqs[] = {
	{ .irq = 139 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_hdq1w_hwmod = {
	.name		= "hdq1w",
	.class		= &am43xx_hdq1w_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_hdq1w_irqs,
	.main_clk	= "func_12m_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_HDQ1W_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_HDQ1W_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'i2c' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_i2c_sysc = {
	.sysc_offs	= 0x0010,
	.syss_offs	= 0x0090,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_CLOCKACTIVITY |
			   SYSC_HAS_ENAWAKEUP | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_i2c_hwmod_class = {
	.name	= "i2c",
	.sysc	= &am43xx_i2c_sysc,
};

/* i2c0 */
static struct omap_hwmod_irq_info am43xx_i2c0_irqs[] = {
	{ .irq = 70 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_i2c0_sdma_reqs[] = {
	{ .name = "txreq", .dma_req = 58 + AM43XX_DMA_REQ_START },
	{ .name = "rxreq", .dma_req = 59 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_i2c0_hwmod = {
	.name		= "i2c0",
	.class		= &am43xx_i2c_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_i2c0_irqs,
	.sdma_reqs	= am43xx_i2c0_sdma_reqs,
	.main_clk	= "uart0_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_I2C0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_I2C0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* i2c1 */
static struct omap_hwmod_irq_info am43xx_i2c1_irqs[] = {
	{ .irq = 71 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_i2c1_sdma_reqs[] = {
	{ .name = "txreq", .dma_req = 60 + AM43XX_DMA_REQ_START },
	{ .name = "rxreq", .dma_req = 61 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_i2c1_hwmod = {
	.name		= "i2c1",
	.class		= &am43xx_i2c_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_i2c1_irqs,
	.sdma_reqs	= am43xx_i2c1_sdma_reqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_I2C1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_I2C1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* i2c2 */
static struct omap_hwmod_irq_info am43xx_i2c2_irqs[] = {
	{ .irq = 30 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_i2c2_hwmod = {
	.name		= "i2c2",
	.class		= &am43xx_i2c_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_i2c2_irqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_I2C2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_I2C2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'mailbox0' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_mailbox0_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0010,
	.sysc_flags	= (SYSC_HAS_RESET_STATUS | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type2,
};

static struct omap_hwmod_class am43xx_mailbox0_hwmod_class = {
	.name	= "mailbox0",
	.sysc	= &am43xx_mailbox0_sysc,
};

/* mailbox0 */
static struct omap_hwmod_irq_info am43xx_mailbox0_irqs[] = {
	{ .irq = 77 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_mailbox0_hwmod = {
	.name		= "mailbox0",
	.class		= &am43xx_mailbox0_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_mailbox0_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MAILBOX0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MAILBOX0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'mcasp' class
 *
 */

static struct omap_hwmod_class am43xx_mcasp_hwmod_class = {
	.name	= "mcasp",
};

/* mcasp0 */
static struct omap_hwmod_irq_info am43xx_mcasp0_irqs[] = {
	{ .name = "txint", .irq = 80 + AM43XX_IRQ_GIC_START },
	{ .name = "rxint", .irq = 81 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_mcasp0_sdma_reqs[] = {
	{ .name = "x_dreq", .dma_req = 8 + AM43XX_DMA_REQ_START },
	{ .name = "r_dreq", .dma_req = 9 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_mcasp0_hwmod = {
	.name		= "mcasp0",
	.class		= &am43xx_mcasp_hwmod_class,
	.clkdm_name	= "l3s_clkdm",
	.mpu_irqs	= am43xx_mcasp0_irqs,
	.sdma_reqs	= am43xx_mcasp0_sdma_reqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MCASP0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MCASP0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* mcasp1 */
static struct omap_hwmod_irq_info am43xx_mcasp1_irqs[] = {
	{ .name = "txint", .irq = 82 + AM43XX_IRQ_GIC_START },
	{ .name = "rxint", .irq = 83 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_mcasp1_sdma_reqs[] = {
	{ .name = "x_dreq", .dma_req = 10 + AM43XX_DMA_REQ_START },
	{ .name = "r_dreq", .dma_req = 11 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_mcasp1_hwmod = {
	.name		= "mcasp1",
	.class		= &am43xx_mcasp_hwmod_class,
	.clkdm_name	= "l3s_clkdm",
	.mpu_irqs	= am43xx_mcasp1_irqs,
	.sdma_reqs	= am43xx_mcasp1_sdma_reqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MCASP1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MCASP1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'mmc' class
 *
 */

static struct omap_hwmod_class am43xx_mmc_hwmod_class = {
	.name	= "mmc",
};

/* mmc0 */
static struct omap_hwmod am43xx_mmc0_hwmod = {
	.name		= "mmc0",
	.class		= &am43xx_mmc_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MMC0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MMC0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* mmc1 */
static struct omap_hwmod am43xx_mmc1_hwmod = {
	.name		= "mmc1",
	.class		= &am43xx_mmc_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MMC1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MMC1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* mmc2 */
static struct omap_hwmod am43xx_mmc2_hwmod = {
	.name		= "mmc2",
	.class		= &am43xx_mmc_hwmod_class,
	.clkdm_name	= "l3s_clkdm",
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_MMC2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_MMC2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'mpu' class
 *
 */

static struct omap_hwmod_class am43xx_mpu_hwmod_class = {
	.name	= "mpu",
};

/* mpu */
static struct omap_hwmod am43xx_mpu_hwmod = {
	.name		= "mpu",
	.class		= &am43xx_mpu_hwmod_class,
	.clkdm_name	= "mpu_clkdm",
	.main_clk	= "dpll_mpu_m2_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_MPU_MPU_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_MPU_MPU_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'ocmcram' class
 *
 */

static struct omap_hwmod_class am43xx_ocmcram_hwmod_class = {
	.name	= "ocmcram",
};

/* ocmcram */
static struct omap_hwmod am43xx_ocmcram_hwmod = {
	.name		= "ocmcram",
	.class		= &am43xx_ocmcram_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_OCMCRAM_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_OCMCRAM_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'otfa' class
 *
 */

static struct omap_hwmod_class am43xx_otfa_hwmod_class = {
	.name	= "otfa",
};

/* otfa_emif */
static struct omap_hwmod am43xx_otfa_emif_hwmod = {
	.name		= "otfa_emif",
	.class		= &am43xx_otfa_hwmod_class,
	.clkdm_name	= "emif_clkdm",
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_OTFA_EMIF_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_OTFA_EMIF_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'pka' class
 *
 */

/* The IP is not compliant to type1 / type2 scheme */
static struct omap_hwmod_sysc_fields omap_hwmod_sysc_type_pka = {
	.sidle_shift	= 4,
	.srst_shift	= 1,
	.autoidle_shift	= 0,
};

static struct omap_hwmod_class_sysconfig am43xx_pka_sysc = {
	.rev_offs	= 0x1f60,
	.sysc_offs	= 0x1f70,
	.syss_offs	= 0x1f74,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type_pka,
};

static struct omap_hwmod_class am43xx_pka_hwmod_class = {
	.name	= "pka",
	.sysc	= &am43xx_pka_sysc,
};

/* pka */
static struct omap_hwmod_irq_info am43xx_pka_irqs[] = {
	{ .irq = 110 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_pka_hwmod = {
	.name		= "pka",
	.class		= &am43xx_pka_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_pka_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_PKA_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_PKA_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'qspi' class
 *
 */

static struct omap_hwmod_class am43xx_qspi_hwmod_class = {
	.name	= "qspi",
};

/* qspi */
static struct omap_hwmod_irq_info am43xx_qspi_irqs[] = {
	{ .irq = 138 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_qspi_hwmod = {
	.name		= "qspi",
	.class		= &am43xx_qspi_hwmod_class,
	.clkdm_name	= "l3s_clkdm",
	.mpu_irqs	= am43xx_qspi_irqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_QSPI_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_QSPI_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'sha' class
 *
 */

static struct omap_hwmod_class am43xx_sha_hwmod_class = {
	.name	= "sha",
};

/* sha0 */
static struct omap_hwmod am43xx_sha0_hwmod = {
	.name		= "sha0",
	.class		= &am43xx_sha_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_SHA0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_SHA0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'smartreflex' class
 *
 */

/* The IP is not compliant to type1 / type2 scheme */
static struct omap_hwmod_sysc_fields omap_hwmod_sysc_type_smartreflex = {
	.sidle_shift	= 24,
	.enwkup_shift	= 26,
};

static struct omap_hwmod_class_sysconfig am43xx_smartreflex_sysc = {
	.sysc_offs	= 0x0038,
	.sysc_flags	= (SYSC_HAS_ENAWAKEUP | SYSC_HAS_SIDLEMODE),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type_smartreflex,
};

static struct omap_hwmod_class am43xx_smartreflex_hwmod_class = {
	.name	= "smartreflex",
	.sysc	= &am43xx_smartreflex_sysc,
};

/* smartreflex0 */
static struct omap_hwmod_irq_info am43xx_smartreflex0_irqs[] = {
	{ .irq = 120 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_smartreflex0_hwmod = {
	.name		= "smartreflex0",
	.class		= &am43xx_smartreflex_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_smartreflex0_irqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_SMARTREFLEX0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_SMARTREFLEX0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* smartreflex1 */
static struct omap_hwmod_irq_info am43xx_smartreflex1_irqs[] = {
	{ .irq = 121 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_smartreflex1_hwmod = {
	.name		= "smartreflex1",
	.class		= &am43xx_smartreflex_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_smartreflex1_irqs,
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_SMARTREFLEX1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_SMARTREFLEX1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'spinlock' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_spinlock_sysc = {
	.sysc_offs	= 0x0010,
	.syss_offs	= 0x0014,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_CLOCKACTIVITY |
			   SYSC_HAS_ENAWAKEUP | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_spinlock_hwmod_class = {
	.name	= "spinlock",
	.sysc	= &am43xx_spinlock_sysc,
};

/* spinlock */
static struct omap_hwmod am43xx_spinlock_hwmod = {
	.name		= "spinlock",
	.class		= &am43xx_spinlock_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_SPINLOCK_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_SPINLOCK_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'synctimer' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_synctimer_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0004,
	.sysc_flags	= SYSC_HAS_SIDLEMODE,
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_synctimer_hwmod_class = {
	.name	= "synctimer",
	.sysc	= &am43xx_synctimer_sysc,
};

/* synctimer */
static struct omap_hwmod am43xx_synctimer_hwmod = {
	.name		= "synctimer",
	.class		= &am43xx_synctimer_hwmod_class,
	.clkdm_name	= "l4_wkup_aon_clkdm",
	.main_clk	= "sys_clkin",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_SYNCTIMER_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_SYNCTIMER_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'timer' class
 *
 */

static struct omap_hwmod_class am43xx_timer_hwmod_class = {
	.name	= "timer",
};

/* timer0 */
static struct omap_hwmod am43xx_timer0_hwmod = {
	.name		= "timer0",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.main_clk	= "timer0_gclk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_TIMER0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_TIMER0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer1 */
static struct omap_hwmod am43xx_timer1_hwmod = {
	.name		= "timer1",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.main_clk	= "timer1_clkmux",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_TIMER1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_TIMER1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer2 */
static struct omap_hwmod am43xx_timer2_hwmod = {
	.name		= "timer2",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer2_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer3 */
static struct omap_hwmod am43xx_timer3_hwmod = {
	.name		= "timer3",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer3_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER3_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER3_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer4 */
static struct omap_hwmod am43xx_timer4_hwmod = {
	.name		= "timer4",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer4_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER4_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER4_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer5 */
static struct omap_hwmod am43xx_timer5_hwmod = {
	.name		= "timer5",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer5_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER5_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER5_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer6 */
static struct omap_hwmod am43xx_timer6_hwmod = {
	.name		= "timer6",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer6_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER6_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER6_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer7 */
static struct omap_hwmod am43xx_timer7_hwmod = {
	.name		= "timer7",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer7_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER7_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER7_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer8 */
static struct omap_hwmod am43xx_timer8_hwmod = {
	.name		= "timer8",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer8_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER8_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER8_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer9 */
static struct omap_hwmod am43xx_timer9_hwmod = {
	.name		= "timer9",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer9_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER9_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER9_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer10 */
static struct omap_hwmod am43xx_timer10_hwmod = {
	.name		= "timer10",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer10_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER10_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER10_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* timer11 */
static struct omap_hwmod am43xx_timer11_hwmod = {
	.name		= "timer11",
	.class		= &am43xx_timer_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.main_clk	= "timer11_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_TIMER11_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_TIMER11_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'tpmss' class
 *
 */

static struct omap_hwmod_class am43xx_tpmss_hwmod_class = {
	.name	= "tpmss",
};

/* tpmss */
static struct omap_hwmod_irq_info am43xx_tpmss_irqs[] = {
	{ .name = "int0", .irq = 122 + AM43XX_IRQ_GIC_START },
	{ .name = "int1", .irq = 156 + AM43XX_IRQ_GIC_START },
	{ .name = "wake", .irq = 167 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_tpmss_hwmod = {
	.name		= "tpmss",
	.class		= &am43xx_tpmss_hwmod_class,
	.clkdm_name	= "tamper_clkdm",
	.mpu_irqs	= am43xx_tpmss_irqs,
	.main_clk	= "div_core_25m_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_TAMPER_TPMSS_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_TAMPER_TPMSS_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'uart' class
 *
 * This class contains several variants: ['uart', 'uart']
 */

static struct omap_hwmod_class_sysconfig am43xx_uart_sysc = {
	.rev_offs	= 0x0050,
	.sysc_offs	= 0x0054,
	.syss_offs	= 0x0058,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_ENAWAKEUP |
			   SYSC_HAS_SIDLEMODE | SYSC_HAS_SOFTRESET |
			   SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_uart_hwmod_class = {
	.name	= "uart",
	.sysc	= &am43xx_uart_sysc,
};

/* uart0 */
static struct omap_hwmod_irq_info am43xx_uart0_irqs[] = {
	{ .irq = 72 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_uart0_sdma_reqs[] = {
	{ .name = "req0", .dma_req = 26 + AM43XX_DMA_REQ_START },
	{ .name = "req1", .dma_req = 27 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_uart0_hwmod = {
	.name		= "uart0",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_uart0_irqs,
	.sdma_reqs	= am43xx_uart0_sdma_reqs,
	.main_clk	= "uart0_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_UART0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_UART0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* uart1 */
static struct omap_hwmod_irq_info am43xx_uart1_irqs[] = {
	{ .irq = 73 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_uart1_sdma_reqs[] = {
	{ .name = "req0", .dma_req = 28 + AM43XX_DMA_REQ_START },
	{ .name = "req1", .dma_req = 29 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_uart1_hwmod = {
	.name		= "uart1",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_uart1_irqs,
	.sdma_reqs	= am43xx_uart1_sdma_reqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_UART1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_UART1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* uart2 */
static struct omap_hwmod_irq_info am43xx_uart2_irqs[] = {
	{ .irq = 74 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_dma_info am43xx_uart2_sdma_reqs[] = {
	{ .name = "req0", .dma_req = 30 + AM43XX_DMA_REQ_START },
	{ .name = "req1", .dma_req = 31 + AM43XX_DMA_REQ_START },
	{ .dma_req = -1 }
};

static struct omap_hwmod am43xx_uart2_hwmod = {
	.name		= "uart2",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_uart2_irqs,
	.sdma_reqs	= am43xx_uart2_sdma_reqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_UART2_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_UART2_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* uart3 */
static struct omap_hwmod_irq_info am43xx_uart3_irqs[] = {
	{ .irq = 44 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_uart3_hwmod = {
	.name		= "uart3",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_uart3_irqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_UART3_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_UART3_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* uart4 */
static struct omap_hwmod_irq_info am43xx_uart4_irqs[] = {
	{ .irq = 45 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_uart4_hwmod = {
	.name		= "uart4",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_uart4_irqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_UART4_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_UART4_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* uart5 */
static struct omap_hwmod_irq_info am43xx_uart5_irqs[] = {
	{ .irq = 46 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_uart5_hwmod = {
	.name		= "uart5",
	.class		= &am43xx_uart_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_uart5_irqs,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_UART5_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_UART5_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'usim' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_usim_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0010,
	.syss_offs	= 0x0014,
	.sysc_flags	= (SYSC_HAS_AUTOIDLE | SYSC_HAS_CLOCKACTIVITY |
			   SYSC_HAS_EMUFREE | SYSC_HAS_ENAWAKEUP |
			   SYSC_HAS_SIDLEMODE | SYSC_HAS_SOFTRESET |
			   SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_usim_hwmod_class = {
	.name	= "usim",
	.sysc	= &am43xx_usim_sysc,
};

/* usim0 */
static struct omap_hwmod_irq_info am43xx_usim0_irqs[] = {
	{ .name = "int", .irq = 84 + AM43XX_IRQ_GIC_START },
	{ .name = "int_cd", .irq = 128 + AM43XX_IRQ_GIC_START },
	{ .name = "phy_int", .irq = 147 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_opt_clk usim0_opt_clks[] = {
	{ .role = "fclk", .clk = "usim0_fclk" },
	{ .role = "fclk32", .clk = "usim0_fclk32" },
};

static struct omap_hwmod am43xx_usim0_hwmod = {
	.name		= "usim0",
	.class		= &am43xx_usim_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_usim0_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_USIM0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_USIM0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
	.opt_clks	= usim0_opt_clks,
	.opt_clks_cnt	= ARRAY_SIZE(usim0_opt_clks),
};

/* usim1 */
static struct omap_hwmod_irq_info am43xx_usim1_irqs[] = {
	{ .name = "int", .irq = 85 + AM43XX_IRQ_GIC_START },
	{ .name = "int_cd", .irq = 129 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod_opt_clk usim1_opt_clks[] = {
	{ .role = "fclk", .clk = "usim1_fclk" },
	{ .role = "fclk32", .clk = "usim1_fclk32" },
};

static struct omap_hwmod am43xx_usim1_hwmod = {
	.name		= "usim1",
	.class		= &am43xx_usim_hwmod_class,
	.clkdm_name	= "l4ls_clkdm",
	.mpu_irqs	= am43xx_usim1_irqs,
	.main_clk	= "core_l4_clkdiv",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_USIM1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_USIM1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
	.opt_clks	= usim1_opt_clks,
	.opt_clks_cnt	= ARRAY_SIZE(usim1_opt_clks),
};

/*
 * 'vpfe' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_vpfe_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0104,
	.sysc_flags	= (SYSC_HAS_MIDLEMODE | SYSC_HAS_SIDLEMODE),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP | MSTANDBY_FORCE | MSTANDBY_NO |
			   MSTANDBY_SMART | MSTANDBY_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type2,
};

static struct omap_hwmod_class am43xx_vpfe_hwmod_class = {
	.name	= "vpfe",
	.sysc	= &am43xx_vpfe_sysc,
};

/* vpfe0 */
static struct omap_hwmod_irq_info am43xx_vpfe0_irqs[] = {
	{ .irq = 48 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_vpfe0_hwmod = {
	.name		= "vpfe0",
	.class		= &am43xx_vpfe_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.mpu_irqs	= am43xx_vpfe0_irqs,
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_VPFE0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_VPFE0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* vpfe1 */
static struct omap_hwmod_irq_info am43xx_vpfe1_irqs[] = {
	{ .irq = 50 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_vpfe1_hwmod = {
	.name		= "vpfe1",
	.class		= &am43xx_vpfe_hwmod_class,
	.clkdm_name	= "l3_clkdm",
	.mpu_irqs	= am43xx_vpfe1_irqs,
	.main_clk	= "sysclk_div",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_PER_VPFE1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_PER_VPFE1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/*
 * 'wdt' class
 *
 */

static struct omap_hwmod_class_sysconfig am43xx_wdt_sysc = {
	.rev_offs	= 0x0000,
	.sysc_offs	= 0x0010,
	.syss_offs	= 0x0014,
	.sysc_flags	= (SYSC_HAS_EMUFREE | SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_SOFTRESET | SYSS_HAS_RESET_STATUS),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART |
			   SIDLE_SMART_WKUP),
	.sysc_fields	= &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class am43xx_wdt_hwmod_class = {
	.name	= "wdt",
	.sysc	= &am43xx_wdt_sysc,
};

/* wdt0 */
static struct omap_hwmod_irq_info am43xx_wdt0_irqs[] = {
	{ .irq = 15 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_wdt0_hwmod = {
	.name		= "wdt0",
	.class		= &am43xx_wdt_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_wdt0_irqs,
	.main_clk	= "wdt0_gclk",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_WDT0_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_WDT0_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};

/* wdt1 */
static struct omap_hwmod_irq_info am43xx_wdt1_irqs[] = {
	{ .irq = 91 + AM43XX_IRQ_GIC_START },
	{ .irq = -1 }
};

static struct omap_hwmod am43xx_wdt1_hwmod = {
	.name		= "wdt1",
	.class		= &am43xx_wdt_hwmod_class,
	.clkdm_name	= "l4_wkup_clkdm",
	.mpu_irqs	= am43xx_wdt1_irqs,
	.main_clk	= "wdt1_clkmux",
	.prcm = {
		.omap4 = {
			.clkctrl_offs = AM43XX_CM_WKUP_WDT1_CLKCTRL_OFFSET,
			.context_offs = AM43XX_RM_WKUP_WDT1_CONTEXT_OFFSET,
			.modulemode   = MODULEMODE_SWCTRL,
		},
	},
};


/*
 * Interfaces
 */

/* mpu -> l3 */
static struct omap_hwmod_ocp_if am43xx_mpu__l3 = {
	.master		= &am43xx_mpu_hwmod,
	.slave		= &am43xx_l3_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> l4_hs */
static struct omap_hwmod_ocp_if am43xx_l3__l4_hs = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_l4_hs_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> l4fw */
static struct omap_hwmod_ocp_if am43xx_l3__l4fw = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_l4fw_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> l4ls */
static struct omap_hwmod_ocp_if am43xx_l3__l4ls = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_l4ls_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> l4wkup */
static struct omap_hwmod_ocp_if am43xx_l3__l4wkup = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_l4wkup_hwmod,
	.clk		= "sys_clkin",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> adc_tsc */
static struct omap_hwmod_ocp_if am43xx_l3__adc_tsc = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_adc_tsc_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_aes0_addrs[] = {
	{
		.pa_start	= 0x53400000,
		.pa_end		= 0x53500fff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l3 -> aes0 */
static struct omap_hwmod_ocp_if am43xx_l3__aes0 = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_aes0_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_aes0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> cefuse */
static struct omap_hwmod_ocp_if am43xx_l4ls__cefuse = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_cefuse_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_control_addrs[] = {
	{
		.pa_start	= 0x44e10000,
		.pa_end		= 0x44e13fff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> control */
static struct omap_hwmod_ocp_if am43xx_l4wkup__control = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_control_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_control_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_cryptodma_addrs[] = {
	{
		.pa_start	= 0x48313000,
		.pa_end		= 0x483133ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> cryptodma */
static struct omap_hwmod_ocp_if am43xx_l4ls__cryptodma = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_cryptodma_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_cryptodma_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_dcan0_addrs[] = {
	{
		.pa_start	= 0x481cc000,
		.pa_end		= 0x481cc1ff,
	},
	{ }
};

/* l4ls -> dcan0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__dcan0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_dcan0_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_dcan0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_dcan1_addrs[] = {
	{
		.pa_start	= 0x481d0000,
		.pa_end		= 0x481d01ff,
	},
	{ }
};

/* l4ls -> dcan1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__dcan1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_dcan1_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_dcan1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_des_addrs[] = {
	{
		.pa_start	= 0x53600000,
		.pa_end		= 0x53700fff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l3 -> des */
static struct omap_hwmod_ocp_if am43xx_l3__des = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_des_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_des_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> dss */
static struct omap_hwmod_ocp_if am43xx_l4ls__dss = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_dss_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> elm */
static struct omap_hwmod_ocp_if am43xx_l4ls__elm = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_elm_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> epwmss1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__epwmss1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_epwmss1_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> epwmss2 */
static struct omap_hwmod_ocp_if am43xx_l4ls__epwmss2 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_epwmss2_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> epwmss3 */
static struct omap_hwmod_ocp_if am43xx_l4ls__epwmss3 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_epwmss3_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> epwmss4 */
static struct omap_hwmod_ocp_if am43xx_l4ls__epwmss4 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_epwmss4_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gfx_addrs[] = {
	{
		.pa_start	= 0x56000000,
		.pa_end		= 0x56000fff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l3 -> gfx */
static struct omap_hwmod_ocp_if am43xx_l3__gfx = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_gfx_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_gfx_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4wkup -> gpio0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__gpio0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_gpio0_hwmod,
	.clk		= "sys_clkin",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gpio1_addrs[] = {
	{
		.pa_start	= 0x4804c000,
		.pa_end		= 0x4804c1ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> gpio1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__gpio1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_gpio1_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_gpio1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gpio2_addrs[] = {
	{
		.pa_start	= 0x481ac000,
		.pa_end		= 0x481ac1ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> gpio2 */
static struct omap_hwmod_ocp_if am43xx_l4ls__gpio2 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_gpio2_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_gpio2_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gpio3_addrs[] = {
	{
		.pa_start	= 0x481ae000,
		.pa_end		= 0x481ae1ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> gpio3 */
static struct omap_hwmod_ocp_if am43xx_l4ls__gpio3 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_gpio3_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_gpio3_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gpio4_addrs[] = {
	{
		.pa_start	= 0x48320000,
		.pa_end		= 0x483201ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> gpio4 */
static struct omap_hwmod_ocp_if am43xx_l4ls__gpio4 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_gpio4_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_gpio4_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_gpio5_addrs[] = {
	{
		.pa_start	= 0x48322000,
		.pa_end		= 0x483221ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> gpio5 */
static struct omap_hwmod_ocp_if am43xx_l4ls__gpio5 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_gpio5_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_gpio5_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> gpmc */
static struct omap_hwmod_ocp_if am43xx_l3__gpmc = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_gpmc_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_hdq1w_addrs[] = {
	{
		.pa_start	= 0x48347000,
		.pa_end		= 0x4834701f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> hdq1w */
static struct omap_hwmod_ocp_if am43xx_l4ls__hdq1w = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_hdq1w_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_hdq1w_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_i2c0_addrs[] = {
	{
		.pa_start	= 0x44e0b000,
		.pa_end		= 0x44e0b0ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> i2c0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__i2c0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_i2c0_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_i2c0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_i2c1_addrs[] = {
	{
		.pa_start	= 0x4802a000,
		.pa_end		= 0x4802a0ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> i2c1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__i2c1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_i2c1_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_i2c1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_i2c2_addrs[] = {
	{
		.pa_start	= 0x4819c000,
		.pa_end		= 0x4819c0ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> i2c2 */
static struct omap_hwmod_ocp_if am43xx_l4ls__i2c2 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_i2c2_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_i2c2_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_mailbox0_addrs[] = {
	{
		.pa_start	= 0x480c8000,
		.pa_end		= 0x480c81ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> mailbox0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__mailbox0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_mailbox0_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_mailbox0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> mcasp0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__mcasp0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_mcasp0_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> mcasp1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__mcasp1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_mcasp1_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> mmc0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__mmc0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_mmc0_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> mmc1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__mmc1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_mmc1_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> mmc2 */
static struct omap_hwmod_ocp_if am43xx_l3__mmc2 = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_mmc2_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> ocmcram */
static struct omap_hwmod_ocp_if am43xx_l3__ocmcram = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_ocmcram_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> otfa_emif */
static struct omap_hwmod_ocp_if am43xx_l3__otfa_emif = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_otfa_emif_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4_hs -> otfa_emif */
static struct omap_hwmod_ocp_if am43xx_l4_hs__otfa_emif = {
	.master		= &am43xx_l4_hs_hwmod,
	.slave		= &am43xx_otfa_emif_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_pka_addrs[] = {
	{
		.pa_start	= 0x48318000,
		.pa_end		= 0x48319fff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> pka */
static struct omap_hwmod_ocp_if am43xx_l4ls__pka = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_pka_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_pka_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> qspi */
static struct omap_hwmod_ocp_if am43xx_l3__qspi = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_qspi_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l3 -> sha0 */
static struct omap_hwmod_ocp_if am43xx_l3__sha0 = {
	.master		= &am43xx_l3_hwmod,
	.slave		= &am43xx_sha0_hwmod,
	.clk		= "sysclk_div",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_smartreflex0_addrs[] = {
	{
		.pa_start	= 0x44e37000,
		.pa_end		= 0x44e3707f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> smartreflex0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__smartreflex0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_smartreflex0_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_smartreflex0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_smartreflex1_addrs[] = {
	{
		.pa_start	= 0x44e39000,
		.pa_end		= 0x44e3907f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> smartreflex1 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__smartreflex1 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_smartreflex1_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_smartreflex1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_spinlock_addrs[] = {
	{
		.pa_start	= 0x480ca000,
		.pa_end		= 0x480cafff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> spinlock */
static struct omap_hwmod_ocp_if am43xx_l4ls__spinlock = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_spinlock_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_spinlock_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_synctimer_addrs[] = {
	{
		.pa_start	= 0x44e86000,
		.pa_end		= 0x44e8601f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> synctimer */
static struct omap_hwmod_ocp_if am43xx_l4wkup__synctimer = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_synctimer_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_synctimer_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4wkup -> timer0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__timer0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_timer0_hwmod,
	.clk		= "sys_clkin",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4wkup -> timer1 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__timer1 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_timer1_hwmod,
	.clk		= "sys_clkin",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer2 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer2 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer2_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer3 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer3 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer3_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer4 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer4 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer4_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer5 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer5 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer5_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer6 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer6 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer6_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer7 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer7 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer7_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer8 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer8 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer8_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer9 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer9 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer9_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer10 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer10 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer10_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> timer11 */
static struct omap_hwmod_ocp_if am43xx_l4ls__timer11 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_timer11_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4wkup -> tpmss */
static struct omap_hwmod_ocp_if am43xx_l4wkup__tpmss = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_tpmss_hwmod,
	.clk		= "div_core_25m_ck",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4wkup -> uart0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__uart0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_uart0_hwmod,
	.clk		= "sys_clkin",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> uart1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__uart1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_uart1_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

/* l4ls -> uart2 */
static struct omap_hwmod_ocp_if am43xx_l4ls__uart2 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_uart2_hwmod,
	.clk		= "core_l4_clkdiv",
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_uart3_addrs[] = {
	{
		.pa_start	= 0x481a6000,
		.pa_end		= 0x481a60ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> uart3 */
static struct omap_hwmod_ocp_if am43xx_l4ls__uart3 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_uart3_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_uart3_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_uart4_addrs[] = {
	{
		.pa_start	= 0x481a8000,
		.pa_end		= 0x481a80ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> uart4 */
static struct omap_hwmod_ocp_if am43xx_l4ls__uart4 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_uart4_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_uart4_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_uart5_addrs[] = {
	{
		.pa_start	= 0x481aa000,
		.pa_end		= 0x481aa0ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> uart5 */
static struct omap_hwmod_ocp_if am43xx_l4ls__uart5 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_uart5_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_uart5_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_usim0_addrs[] = {
	{
		.pa_start	= 0x48034000,
		.pa_end		= 0x480340ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> usim0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__usim0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_usim0_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_usim0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_usim1_addrs[] = {
	{
		.pa_start	= 0x48036000,
		.pa_end		= 0x480360ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> usim1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__usim1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_usim1_hwmod,
	.clk		= "core_l4_clkdiv",
	.addr		= am43xx_usim1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_vpfe0_addrs[] = {
	{
		.pa_start	= 0x48326000,
		.pa_end		= 0x483261ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> vpfe0 */
static struct omap_hwmod_ocp_if am43xx_l4ls__vpfe0 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_vpfe0_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_vpfe0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_vpfe1_addrs[] = {
	{
		.pa_start	= 0x48328000,
		.pa_end		= 0x483281ff,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4ls -> vpfe1 */
static struct omap_hwmod_ocp_if am43xx_l4ls__vpfe1 = {
	.master		= &am43xx_l4ls_hwmod,
	.slave		= &am43xx_vpfe1_hwmod,
	.clk		= "sysclk_div",
	.addr		= am43xx_vpfe1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_wdt0_addrs[] = {
	{
		.pa_start	= 0x44e33000,
		.pa_end		= 0x44e3307f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> wdt0 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__wdt0 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_wdt0_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_wdt0_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_addr_space am43xx_wdt1_addrs[] = {
	{
		.pa_start	= 0x44e35000,
		.pa_end		= 0x44e3507f,
		.flags		= ADDR_TYPE_RT
	},
	{ }
};

/* l4wkup -> wdt1 */
static struct omap_hwmod_ocp_if am43xx_l4wkup__wdt1 = {
	.master		= &am43xx_l4wkup_hwmod,
	.slave		= &am43xx_wdt1_hwmod,
	.clk		= "sys_clkin",
	.addr		= am43xx_wdt1_addrs,
	.user		= OCP_USER_MPU | OCP_USER_SDMA,
};

static struct omap_hwmod_ocp_if *am43xx_hwmod_ocp_ifs[] __initdata = {
	&am43xx_mpu__l3,
	&am43xx_l3__l4_hs,
	&am43xx_l3__l4fw,
	&am43xx_l3__l4ls,
	&am43xx_l3__l4wkup,
	&am43xx_l3__adc_tsc,
	&am43xx_l3__aes0,
	&am43xx_l4ls__cefuse,
	&am43xx_l4wkup__control,
	&am43xx_l4ls__cryptodma,
	&am43xx_l4ls__dcan0,
	&am43xx_l4ls__dcan1,
	&am43xx_l3__des,
	&am43xx_l4ls__dss,
	&am43xx_l4ls__elm,
	&am43xx_l4ls__epwmss1,
	&am43xx_l4ls__epwmss2,
	&am43xx_l4ls__epwmss3,
	&am43xx_l4ls__epwmss4,
	&am43xx_l3__gfx,
	&am43xx_l4wkup__gpio0,
	&am43xx_l4ls__gpio1,
	&am43xx_l4ls__gpio2,
	&am43xx_l4ls__gpio3,
	&am43xx_l4ls__gpio4,
	&am43xx_l4ls__gpio5,
	&am43xx_l3__gpmc,
	&am43xx_l4ls__hdq1w,
	&am43xx_l4wkup__i2c0,
	&am43xx_l4ls__i2c1,
	&am43xx_l4ls__i2c2,
	&am43xx_l4ls__mailbox0,
	&am43xx_l4ls__mcasp0,
	&am43xx_l4ls__mcasp1,
	&am43xx_l4ls__mmc0,
	&am43xx_l4ls__mmc1,
	&am43xx_l3__mmc2,
	&am43xx_l3__ocmcram,
	&am43xx_l3__otfa_emif,
	&am43xx_l4_hs__otfa_emif,
	&am43xx_l4ls__pka,
	&am43xx_l3__qspi,
	&am43xx_l3__sha0,
	&am43xx_l4wkup__smartreflex0,
	&am43xx_l4wkup__smartreflex1,
	&am43xx_l4ls__spinlock,
	&am43xx_l4wkup__synctimer,
	&am43xx_l4wkup__timer0,
	&am43xx_l4wkup__timer1,
	&am43xx_l4ls__timer2,
	&am43xx_l4ls__timer3,
	&am43xx_l4ls__timer4,
	&am43xx_l4ls__timer5,
	&am43xx_l4ls__timer6,
	&am43xx_l4ls__timer7,
	&am43xx_l4ls__timer8,
	&am43xx_l4ls__timer9,
	&am43xx_l4ls__timer10,
	&am43xx_l4ls__timer11,
	&am43xx_l4wkup__tpmss,
	&am43xx_l4wkup__uart0,
	&am43xx_l4ls__uart1,
	&am43xx_l4ls__uart2,
	&am43xx_l4ls__uart3,
	&am43xx_l4ls__uart4,
	&am43xx_l4ls__uart5,
	&am43xx_l4ls__usim0,
	&am43xx_l4ls__usim1,
	&am43xx_l4ls__vpfe0,
	&am43xx_l4ls__vpfe1,
	&am43xx_l4wkup__wdt0,
	&am43xx_l4wkup__wdt1,
	NULL,
};

int __init am43xx_hwmod_init(void)
{
	omap_hwmod_init();
	return omap_hwmod_register_links(am43xx_hwmod_ocp_ifs);
}

