/*
 * AM43xx Power Management register bits
 *
 * Copyright (C) 2013 Texas Instruments Incorporated - http://www.ti.com
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ARCH_ARM_MACH_OMAP2_PRM_REGBITS_43XX_H
#define __ARCH_ARM_MACH_OMAP2_PRM_REGBITS_43XX_H

/* Used by REVISION_PRM */
#define AM43XX_CUSTOM_SHIFT			6
#define AM43XX_CUSTOM_WIDTH			0x2
#define AM43XX_CUSTOM_MASK			(0x3 << 6)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_CORE_RECAL_EN_SHIFT		12
#define AM43XX_DPLL_CORE_RECAL_EN_WIDTH		0x1
#define AM43XX_DPLL_CORE_RECAL_EN_MASK		(1 << 12)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_CORE_RECAL_ST_SHIFT		12
#define AM43XX_DPLL_CORE_RECAL_ST_WIDTH		0x1
#define AM43XX_DPLL_CORE_RECAL_ST_MASK		(1 << 12)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_DDR_RECAL_EN_SHIFT		14
#define AM43XX_DPLL_DDR_RECAL_EN_WIDTH		0x1
#define AM43XX_DPLL_DDR_RECAL_EN_MASK		(1 << 14)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_DDR_RECAL_ST_SHIFT		14
#define AM43XX_DPLL_DDR_RECAL_ST_WIDTH		0x1
#define AM43XX_DPLL_DDR_RECAL_ST_MASK		(1 << 14)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_DISP_RECAL_EN_SHIFT		15
#define AM43XX_DPLL_DISP_RECAL_EN_WIDTH		0x1
#define AM43XX_DPLL_DISP_RECAL_EN_MASK		(1 << 15)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_DISP_RECAL_ST_SHIFT		13
#define AM43XX_DPLL_DISP_RECAL_ST_WIDTH		0x1
#define AM43XX_DPLL_DISP_RECAL_ST_MASK		(1 << 13)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_EXTDEV_RECAL_EN_SHIFT	16
#define AM43XX_DPLL_EXTDEV_RECAL_EN_WIDTH	0x1
#define AM43XX_DPLL_EXTDEV_RECAL_EN_MASK	(1 << 16)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_EXTDEV_RECAL_ST_SHIFT	16
#define AM43XX_DPLL_EXTDEV_RECAL_ST_WIDTH	0x1
#define AM43XX_DPLL_EXTDEV_RECAL_ST_MASK	(1 << 16)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_MPU_RECAL_EN_SHIFT		11
#define AM43XX_DPLL_MPU_RECAL_EN_WIDTH		0x1
#define AM43XX_DPLL_MPU_RECAL_EN_MASK		(1 << 11)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_MPU_RECAL_ST_SHIFT		11
#define AM43XX_DPLL_MPU_RECAL_ST_WIDTH		0x1
#define AM43XX_DPLL_MPU_RECAL_ST_MASK		(1 << 11)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_DPLL_PER_RECAL_EN_SHIFT		13
#define AM43XX_DPLL_PER_RECAL_EN_WIDTH		0x1
#define AM43XX_DPLL_PER_RECAL_EN_MASK		(1 << 13)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_DPLL_PER_RECAL_ST_SHIFT		15
#define AM43XX_DPLL_PER_RECAL_ST_WIDTH		0x1
#define AM43XX_DPLL_PER_RECAL_ST_MASK		(1 << 15)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_FORCEWKUP_EN_SHIFT		10
#define AM43XX_FORCEWKUP_EN_WIDTH		0x1
#define AM43XX_FORCEWKUP_EN_MASK		(1 << 10)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_FORCEWKUP_ST_SHIFT		10
#define AM43XX_FORCEWKUP_ST_WIDTH		0x1
#define AM43XX_FORCEWKUP_ST_MASK		(1 << 10)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_FREQ_UPDATE_EN_SHIFT		0
#define AM43XX_FREQ_UPDATE_EN_WIDTH		0x1
#define AM43XX_FREQ_UPDATE_EN_MASK		(1 << 0)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_FREQ_UPDATE_ST_SHIFT		0
#define AM43XX_FREQ_UPDATE_ST_WIDTH		0x1
#define AM43XX_FREQ_UPDATE_ST_MASK		(1 << 0)

/* Used by REVISION_PRM */
#define AM43XX_FUNC_SHIFT			16
#define AM43XX_FUNC_WIDTH			0xc
#define AM43XX_FUNC_MASK			(0xfff << 16)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_IO_EN_SHIFT			9
#define AM43XX_IO_EN_WIDTH			0x1
#define AM43XX_IO_EN_MASK			(1 << 9)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_IO_ST_SHIFT			9
#define AM43XX_IO_ST_WIDTH			0x1
#define AM43XX_IO_ST_MASK			(1 << 9)

/* Used by REVISION_PRM */
#define AM43XX_R_RTL_SHIFT			11
#define AM43XX_R_RTL_WIDTH			0x5
#define AM43XX_R_RTL_MASK			(0x1f << 11)

/* Used by REVISION_PRM */
#define AM43XX_SCHEME_SHIFT			30
#define AM43XX_SCHEME_WIDTH			0x2
#define AM43XX_SCHEME_MASK			(0x3 << 30)

/* Used by PRM_IRQENABLE_M3, PRM_IRQENABLE_MPU */
#define AM43XX_TRANSITION_EN_SHIFT		8
#define AM43XX_TRANSITION_EN_WIDTH		0x1
#define AM43XX_TRANSITION_EN_MASK		(1 << 8)

/* Used by PRM_IRQSTATUS_M3, PRM_IRQSTATUS_MPU */
#define AM43XX_TRANSITION_ST_SHIFT		8
#define AM43XX_TRANSITION_ST_WIDTH		0x1
#define AM43XX_TRANSITION_ST_MASK		(1 << 8)

/* Used by REVISION_PRM */
#define AM43XX_X_MAJOR_SHIFT			8
#define AM43XX_X_MAJOR_WIDTH			0x3
#define AM43XX_X_MAJOR_MASK			(0x7 << 8)

/* Used by REVISION_PRM */
#define AM43XX_Y_MINOR_SHIFT			0
#define AM43XX_Y_MINOR_WIDTH			0x6
#define AM43XX_Y_MINOR_MASK			(0x3f << 0)
#endif
